#include <iostream>
#include <cmath>
using namespace std;

/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.


*/

double T(double n);

bool isPentagonal(double Tn);
bool isHexagonal(double Tn);

int main() {
    double i = 286;
    double answer = T(i);
    while(!isPentagonal(answer) || !isHexagonal(answer)) {
        i++;
        answer = T(i);
    }
    cout << long(answer) << endl;

    return 0;
}

double T(double n) {
    return n*(n+1)/2;
}

bool isPentagonal(double Tn) {
    // Pn = n(3n-1)/2 --> 3n^2 - n - 2Pn = 0
    double n = (1.0 + sqrt(1.0 + 24.0*Tn))/6.0;
    return n == int(n);
}

bool isHexagonal(double Tn) {
    // Hn = n(2n-1) --> 2n^2 - n - Hn = 0
    double n = (1.0 + sqrt(1.0 + 8*Tn))/4.0;
    return n == int(n);
}
